# Generated by Django 3.0.1 on 2019-12-27 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('has_disconnected', models.BooleanField(default=False)),
                ('category', models.TextField(choices=[('loan_approval', 'Loan approval'), ('loan_disbursement', 'Loan disbursement'), ('general_info', 'General information inquiry'), ('info_update', 'User information update'), ('undetermined', 'Not determined')], default='undetermined', max_length=140)),
                ('priority', models.PositiveIntegerField(default=50)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('resolved', 'Resolved'), ('waiting', 'Waiting')], default='waiting', max_length=60)),
                ('subject', models.TextField(max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=500)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='chat.Ticket')),
            ],
        ),
    ]
